server:
  port: 8081

spring:
  application:
    name: token-jwt-simplificado
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

token:
  jwt:
    secret: 1scpnYJdPYmF+OqJiNmoNAVFtPcTz7VWQSJrpzDM/mg=
    expiration: 14400000